### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by pedro-lb** [DannyBen/alf#25]
The README doesn't make it clear on how to uninstall, maybe we could improve this.

**Comment by DannyBen** [comment]
Sure, will do later today.

It should just be removing `/usr/local/bin/alf` and `~/.alfrc`

**Comment by pedro-lb** [comment]
Thanks @DannyBen for the (really) fast reply!

**Comment by DannyBen** [comment]
[Done](https://github.com/DannyBen/alf#uninstalling).

In addition, I also [clarified in the features section](https://github.com/DannyBen/alf#features) that alf does not alter your system in any way - other than create the `~/.bash_aliases` when you run `alf save`. 

Thanks for your suggestion, and let me know if you face any other issues or have any other question.
