### ISSUE TITLE
Feature Request: completion

### ISSUE THREAD

**Issue by planetceres** [DannyBen/alf#28]
This is a handy utility! Would be even better if this had bash completion like opcode. Any chance of that getting added as a feature?

Thanks for sharing it.

**Comment by DannyBen** [comment]
Well, I feel that with alf it is much less necessary than opcode, since:

1. opcode is on a per project basis, so completion helps you remember what you have
2. alf was designed so that you can make short intuitive shortcuts. if it needs completion, it is too long.

However, I am open to it.

**Comment by DannyBen** [comment]
Hey - I think this can be easily achieved, by doing this:

I can make `alf generate` also append completion commands to the end of the result (which normally goes into `~/.bash_aliases`.

Something like this will be appended for each command:

```
complete -W "SUBCOMMANDS" COMMAND
```

So, for an alf configuration like this:

```
g: git
  s: status
  co: checkout
  new: checkout -b
```

the completion line will look like this:

```
complete -W "s co new" g
```

Thoughts?

I will try to implement it.

**Comment by DannyBen** [comment]
If you want, you can try the [alf script from the add/completion branch](https://github.com/DannyBen/alf/blob/add/completion/alf)

It will append completion commands to the end of the generated bash_aliases script.

You can see it by running

```shell
$ alf generate
```

or save it by running

```shell
$ alf save && source ~/.bash_aliases
```

It adds completion to subcommands.
Completion for main commands is automatically enabled by bash

Is this what you meant?

**Comment by planetceres** [comment]
This is great! Exactly what I was asking for.

**Comment by DannyBen** [comment]
Great. It is released already in master.
