### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by ri-ceres** [DannyBen/alf#30]
Hi, I noticed that both alf and [opcode](https://github.com/DannyBen/opcode) are built with [bashly](https://github.com/DannyBen/bashly) which is MIT licensed. Does the same license apply to these projects as well?

**Comment by DannyBen** [comment]
How amateurish of me... yes, of course :)
I will add a license immediately.

(and opcode is not built with bashly, [Rush](https://github.com/DannyBen/rush-cli) is)

**Comment by ri-ceres** [comment]
Fantastic. Thanks!

**Comment by DannyBen** [comment]
Cool. I am closing, feel free to reopen or ask anything else in a separate issue.
Enjoy.
