### ISSUE TITLE
Connect alf to any existing repository with an alf.conf 

### ISSUE THREAD

**Issue by dallenbaldwin** [DannyBen/alf#49]
Newbie here.

I already have a repository set up to hold all my Linux setup scripts and putting my `alf.conf` in there just makes sense. 

However, when I use `alf connect {user}/{repo}` it creates a new repo inside instead of connecting the exisiting repo.

Is there a way to use `alf connect` with an existing repository that already has a `alf.conf`? 

![image](https://user-images.githubusercontent.com/14098845/216790691-8400aba4-3eaf-4fd2-93ae-7b3ff2d1aad4.png)

![image](https://user-images.githubusercontent.com/14098845/216790724-261551ff-dd36-4f09-8683-065d7f828b16.png)

**Comment by DannyBen** [comment]
Well, all you need to do is write the path that contains your alf conf to a file named `.alfrc` in your home directory.
Something like `echo path/to/alf-conf/dir > ~/.alfrc`

**Comment by dallenbaldwin** [comment]
Ah! I'll give that a try. Thank you 😊

**Comment by DannyBen** [comment]
I am assuming you have succeeded, if you need further help feel free to reply.
