### ISSUE TITLE
How many levels can we go?

### ISSUE THREAD

**Issue by madorian** [DannyBen/alf#56]
Is a third level possible?

Something like: 

```
s: !
  q: !
    x: ls

```

**Comment by DannyBen** [comment]
Currently, no - only 2 - but let me see if I can add more, I can see the value, just not sure it will be easy to implement.

**Comment by DannyBen** [comment]
At this point, I am not going to extend the nesting to more than the single level. I could not find a satisfactory implementation. If anyone comes up with a suggestion, I am open to discussing it again.
