### ISSUE TITLE
Can we somehow show the aliases?

### ISSUE THREAD

**Issue by madorian** [DannyBen/alf#57]
I know that I can look in the alf configuration, but is there any way to list the possibilities on the command line?

**Comment by DannyBen** [comment]
There is `alf edit` and `alf which CODE [SUBCODE]`.

Showing just the aliases could be very cryptic without knowing what they do + they have subcodes.

I am open to adding `alf show` or something similar, but I am not convinced it will be useful, especially not if you have a [large alf.conf file like me](https://github.com/DannyBen/alf-conf/blob/master/alf.conf).

Can you show a sample output you expect?

**Comment by madorian** [comment]
Just showing the aliases would be helpful, instead of opening the configuration file, which can be very big, for example for s:
```
s show
q: ssh quasar
s: ssh spartacus
```

**Comment by DannyBen** [comment]
I don't understand the output you provided. It seems like you want to see the command of the alias "s" but you also show the output for the alias "q". 

If you want to see the command of a single alias, use `alf which` or `alf w`. Provide it with a code, and an optional subcode.

```bash
$ alf which g
git

$ alf w g s
git status
```

Applying a "show" command to any alias (i.e. `g show`) cannot happen, simply for the reason that supplied arguments are passed on to the function, so you can do things like this:

```bash
$ alf which g c
git add . --all && git commit -am

$ g c "Commit message"
```
